# 
FROM alpine:latest
LABEL author="ToshiNamura"
LABEL minecraft.version="1.16.5"
LABEL purpur.build.id="1171"
LABEL purpur.build.date="18.06.21, 05:27:22"

# 
EXPOSE 25565
VOLUME [ "/purpur" ]

# 
RUN apk add --no-cache --upgrade bash
RUN apk add openjdk17-jdk

# 
WORKDIR /purpur
COPY ./Purpur-1.16.5-1171/purpur-1.16.5-1171.jar .
COPY ./settings/server.properties .
COPY ./settings/eula.txt .
COPY ./settings/whitelist.json .
COPY ./settings/ops.json .

#
ENV JAVA_XMS_MEMORY="-Xms2G"
ENV JAVA_XMX_MEMORY="-Xmx2G"
ENV JAVA_COMMAND_LINE=""
ENV PURPUR_JAR_FILE="purpur-1.16.5-1171.jar"
ENV PURPUR_COMMAND_LINE="--nogui"

# 
ADD ./settings/starting.sh /purpur
CMD [ "bash", "/purpur/starting.sh" ]